name: Build and deploy Node.js app to Azure Web App - SpinRecordsEste

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Comprimir el contenido de la carpeta build/ en un archivo tar.gz
      - name: Create tar.gz artifact for deployment
        run: |
          cd build
          tar -czf ../release.tar.gz ./*

      # Subir el archivo tar.gz como artefacto
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Descargar el artefacto desde el paso anterior
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Extraer el contenido del archivo tar.gz
      - name: Extract tar.gz artifact for deployment
        run: |
          tar -xzf release.tar.gz
          cd build

      # Login a Azure usando las credenciales secretas
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Desplegar la aplicación en Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SpinRecordsEste'
          slot-name: 'Production'
          package: ./build
